server:
  port: 8888

spring:

  datasource:
    url: jdbc:mysql://xxx?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username:
    password:
    driver-class-name:
    type:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name:
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
mybatis:
  mapper-locations: classpath:mapper/*.xml
kafka-config:
  host:
  port:
  group_id:

akka-config:
  actor_path: akka://test-project/user/
  actorSystem_name: test-project
